
# This is a basic workflow for terraform 
name: terraform CI
on:
  push:
    branches:
      - github-action

  pull_request:
    branches:
      - github-action

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check Azure Account
        run: az account show

      - name: Check Terraform Version
        run: terraform version

      - name: Terraform Init
        working-directory: Environment/Dev
        run: terraform init

      - name: Terraform validate
        working-directory: Environment/Dev
        run: terraform validate

      - name: terraform fmt
        working-directory: Environment/Dev
        run: terraform fmt -check -recursive

      - name: terraform Debug
        working-directory: Environment/Dev
        run: |
          terraform providers
          terraform state list || true 

      - name: terraform plan
        working-directory: Environment/Dev
        run: terraform plan -input=false
    
        timeout-minutes: 15


  lint:
    name: Lint
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Terraform Code
        uses: "infinite-automations/tflint-all-in-one@v1.0.1"
        with:
          directory: "./Environment/Dev"      
   
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest   
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12

        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2

        if: success() || failure()
        with:
          sarif_file: results.sarif

     


