# This is a basic workflow for terraform 
name: terraform CI

on:
  push:
    branches:
     - main
  pull_request:
    branches:
      - main   
jobs:
  terraform_init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: terraform init
        run: init
    
     
     
