# This is a basic workflow for terraform 
name: terraform CI

on:
  push:
    branches:
     - github-action
  pull_request:
    branches:
      - github-action   
jobs:
  terraform:
    name: terraform CI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v3
        
    - name: Check Terraform Version
      run: terraform version
  
    - name: Terraform Init
      working-directory: Environment/Dev
      run: terraform init
   
     
     
